version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  worker:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=flask_app
      - FLASK_DEBUG=0
    volumes:
      - ./.env:/app/.env
    command: poetry run celery -A app.worker worker -B
    # command: poetry run celery -A app.worker worker -B --loglevel=INFO

    depends_on:
      - redis

  redis:
    restart: always
    image: 'redis:alpine'
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}

  app:
    build: .
    # restart: always
    expose:
      - 5000
    # volumes:
    #   - ./:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - FLASK_APP=flask_app
      - FLASK_DEBUG=0
    ports:
      - 127.0.0.1:7777:5000
    command: ./start_server.sh

volumes:
  db_data:
