version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nitrix
    ports:
      - 127.0.0.1:54321:5432

  app:
    build: .
    # restart: always
    expose:
      - 5000
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - FLASK_APP=flask_app
      - FLASK_DEBUG=0
    ports:
      - 127.0.0.1:5555:5000
    command: flask run -h 0.0.0.0

volumes:
  db_data:
