"""change id from int to strings invoice

Revision ID: 47f7501c4dd4
Revises: 9e9fa68cc187
Create Date: 2021-11-16 11:21:36.665337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f7501c4dd4'
down_revision = '9e9fa68cc187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'ninja_product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('reseller_product', 'ninja_product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('resellers', 'ninja_client_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resellers', 'ninja_client_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('reseller_product', 'ninja_product_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('phones', 'ninja_product_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
