"""empty message

Revision ID: 9e9fa68cc187
Revises: 027e6433c105
Create Date: 2021-11-10 17:29:55.046032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e9fa68cc187'
down_revision = '027e6433c105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.Enum('creation_account', 'deletion_account', 'changes_account', 'creation_reseller', 'deletion_reseller', 'changes_reseller', 'creation_product', 'deletion_product', 'changes_product', name='edittype'), nullable=True),
    sa.Column('value_name', sa.String(length=64), nullable=True),
    sa.Column('before_value_str', sa.String(length=64), nullable=True),
    sa.Column('after_value_str', sa.String(length=64), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('account_changes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_changes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('change_type', postgresql.ENUM('sim', 'name', 'imei', 'product', 'phone', 'reseller', 'months', 'activation_date', 'created', 'deleted', name='changetype'), autoincrement=False, nullable=True),
    sa.Column('value_str', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('new_value_str', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_changes_account_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='account_changes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_changes_pkey')
    )
    op.drop_table('history_changes')
    # ### end Alembic commands ###
