"""empty message

Revision ID: cc96fd7c4932
Revises: 
Create Date: 2020-07-21 14:27:03.565170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc96fd7c4932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_changes', sa.Column('new_value_str', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_changes', 'new_value_str')
    # ### end Alembic commands ###
